### ISSUE TITLE
Add Blueprint formatter

### ISSUE THREAD

**Issue by sonnyp** [workbenchdev/Workbench#214]
We auto format Code / Style on Run, let's do the same for Blueprint.

Maybe we should add a button too - "Run" is not visble if "Code" panel is hidden.

An other option is to move the "Run" button to the Window header bar. Which would remove the need for "Reload" button for UI on https://github.com/sonnyp/Workbench/issues/213

**Comment by sonnyp** [comment]
Now that Workbench is fully sandboxed - it's not as much a big deal to run Code even if it's hidden.

We can also add an indicator that there is hidden code/style/ui if the panel is closed.

**Comment by jameswestman** [comment]
I'd like to add this to the language server eventually.

**Comment by sonnyp** [comment]
@gergorni is working on a formatter for Blueprint :partying_face: 

* https://gitlab.gnome.org/jwestman/blueprint-compiler/-/issues/116
* https://gitlab.gnome.org/jwestman/blueprint-compiler/-/merge_requests/124

**Comment by gregorni** [comment]
I believe this is closed with the latest release.
