### ISSUE TITLE
Preview window doesn't close sometimes

### ISSUE THREAD

**Issue by gregorni** [workbenchdev/Workbench#745]
This shows up with the current state of #744 and #742. When you run the demo, the preview window opens, but then you can't close it, even if you close all other Workbench windows. 

When running such previews, there's a warning message in the terminal:
```
(process:196): Gtk-WARNING **: 18:11:28.728: A window is shown after it has been destroyed. This will leave the window in an inconsistent state.
```

**Comment by theCapypara** [comment]
Looking at the affected demos, this is most likely an issue with demos that have windows as top-level components (meaning the previewer doesn't explicitly have to create it).
